### PR TITLE
Add outreach at ERAD

### PR DESCRIPTION
**Pull request by bart1**
@nwhpt shall I also add your presentation?

@peterdesmet I do not directly have a background image, I guess without one in the yaml it wont break?

### CODE REVIEW

**Comment by bart1** [comment]
PS should we also add the abstracts?

**Comment by nwhpt** [comment]
Thanks, you can add the citation of the talk. However, the work was partly financed by a wind energy company and I want to be cautious with some of the material, i.e. no downloadable presentation, if that's what you meant.

**Comment by bart1** [comment]
It would be just the title

**Comment by peterdesmet** [comment]
Page will be live soon at https://hirad.science/outreach/

**Pull request merged**
